# Font
font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font Bold
italic_font      FiraCode Nerd Font Light
font_size        12.0

# Okno
background_opacity 0.92
window_padding_width 10

# Kolory ze smoka
foreground              #D0ECE8
background              #0A0F0E
selection_foreground    #0A0F0E
selection_background    #00E5C8

# Kursor
cursor                  #00E5C8
cursor_text_color       #0A0F0E
cursor_blink_interval   0

# Kolory terminala
# Czarny
color0  #111A18
color8  #243A34
# Czerwony
color1  #ff6b6b
color9  #ff8080
# Zielony
color2  #2D5C52
color10 #00B39E
# Żółty
color3  #e5c07b
color11 #f0c070
# Niebieski
color4  #007A6E
color12 #007A6E
# Magenta
color5  #7AB5AD
color13 #00E5C8
# Cyjan
color6  #00B39E
color14 #00FFEE
# Biały
color7  #D0ECE8
color15 #ffffff

# Zachowanie
enable_audio_bell no
copy_on_select yes
